class AppInternalError(Exception):
    pass


class Error(AppInternalError):
    pass
